### ISSUE TITLE
CLI SCOUT-AUDIT  --OUT-FORMAT

### ISSUE THREAD

**Issue by polblancoo** [CoinFabrik/scout-audit#125]
# cargo scout -audit - out-format , does not work, 
the short Yes .# cargo scout-audit -o [format]

**Comment by matiascabello** [comment]
Hey @polblancoo, thanks for reporting this! We're working on it and it will be fixed shortly.

Feel free to add any other feedback on the tool.

**Comment by polblancoo** [comment]
Great job, I met them on Polkadecode, which is online. If you're okay with it, I'll do a review for subsocial.
_------
gran trabajo , los conoci en el polkadecode que estan online , si les parece bien  hago review para subsocial .
